defaults:
  - hydra: default
  - _self_

save_dir: "logs/"
seed: 1

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  entity: guillaume-rabusseau 
  project: deep-linear-rnn 
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  save_dir: ${save_dir}
  offline: False
  tags: null

train_dataset:
  _target_: dataset.SyntheticCopyDataset
  n_samples: 1000
  seq_len: 10
  vocab_size: 2 
  lookahead: 6
  datatype: "real"
  copymode: "linear"

val_dataset:
  _target_: dataset.SyntheticCopyDataset
  n_samples: 200
  seq_len: 10
  vocab_size: 2 
  lookahead: 6
  datatype: "real"
  copymode: "linear"

test_dataset:
  _target_: dataset.SyntheticCopyDataset
  n_samples: 200
  seq_len: 10
  vocab_size: 2 
  lookahead: 6
  datatype: "real"
  copymode: "linear"

datamodule:
  _target_: dataset.SyntheticCopyDataModule
  batch_size: 2
  train_dataset: ${train_dataset}
  val_dataset: ${val_dataset}
  test_dataset: ${test_dataset}

trainer:
  max_epochs: 200 
  enable_progress_bar: True
  log_every_n_steps: 10
  limit_train_batches: 0.1
  accelerator: "cpu"

model:
  _target_: model.S4Model
  d_input: ${train_dataset.vocab_size}
  d_output: ${train_dataset.vocab_size}
  d_model: 64 
  n_layers: 4
  prenorm: True
  dropout: 0.0

callbacks:
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    patience: 1000
    mode: min
    verbose: True

task :
  _target_: task.CopyTaskRegression
  model: ${model}
  lr: 1e-3
